version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: documentary_api
    ports:
      - "5032:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=database;Database=documentarydb;Username=postgres;Password=password
    depends_on:
      - database

  database:
    image: postgres:15
    container_name: documentary_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: documentarydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrations:
    build:
      context: .
      dockerfile: Dockerfile.migrations
    container_name: documentary_migrations
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=database;Database=documentarydb;Username=postgres;Password=password
    depends_on:
      - database
    entrypoint: [ "/bin/bash" ]
    tty: true
    volumes:
      - .:/app

volumes:
  postgres_data: